### PR TITLE
[GLUTEN-6849][VL] Call static initializers once in Spark local mode / when session is renewed

### LINKED ISSUE #6849: [VL] Move process-wise static initializers out from VeloxListenerApi
### Description

We have some process-wise static initializers defined in `VeloxListenerApi` or `GlutenPlugin` which works in both Driver/Executor's initializations. This doesn't work well since in Spark local mode the initializers are called twice which is unnecessary and needs synchronizations. 

We should move the initializers that is expected to be run once in the same process out from the places and guard them in some kind of static blocks (e.g. Scala object initialization block).

### PR DESCRIPTION
**Pull request by zhztheplayer**
In Spark local mode, Spark driver and executor are both calling ListenerApi to run static initializers. This could cause UBs in some cases since the initializers were not deigned to be called more than once. This patch fixes the issue by adding a check `inLocalMode` then use it to skip executor side initializer when it's true.

The patch also avoids rerunning the static initializers when Spark session is recreated.

And with essential code cleanups.

Closes #6849

### CODE REVIEW

File: backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala [hunk 1]
```diff
@@ -191,4 +137,42 @@ class VeloxListenerApi extends ListenerApi {
...
+  // See org.apache.spark.SparkMasterRegex
+  private val LOCAL_N_REGEX = """local\[([0-9]+|\*)\]""".r
+  private val LOCAL_N_FAILURES_REGEX = """local\[([0-9]+|\*)\s*,\s*([0-9]+)\]""".r
+
+  // TODO: Implement graceful shutdown and remove these flags.
+  //  As spark conf may change when active Spark session is recreated.
+  private val driverInitialized: AtomicBoolean = new AtomicBoolean(false)
+  private val executorInitialized: AtomicBoolean = new AtomicBoolean(false)
+
+  private def inLocalMode(conf: SparkConf): Boolean = {
```
Comment (jackylee-ch) [inline backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:150]: nit: This can be can changed to the same code as `Utils.isLocalMaster`.
```
  def isLocalMaster(conf: SparkConf): Boolean = {
    val master = conf.get("spark.master", "")
    master == "local" || master.startsWith("local[")
  }
```

Comment (zhztheplayer) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:150]: Super helpful. Thanks.

File: backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala [hunk 2]
```diff
@@ -27,138 +26,67 @@ import org.apache.gluten.vectorized.{JniLibLoader, JniWorkspace}
...
-      val systemNamePattern(systemName) =
-        systemInfoLines.find(_.startsWith("NAME=")).getOrElse("")
-      val systemVersionPattern(systemVersion) =
-        systemInfoLines.find(_.startsWith("VERSION=")).getOrElse("")
-      if (systemName.isEmpty || systemVersion.isEmpty) {
-        throw new GlutenException("Failed to get OS name and version info.")
-      }
-      getLibraryLoaderForOS(systemName, systemVersion, system)
+    val conf = pc.conf
+    if (inLocalMode(conf)) {
```
Comment (jackylee-ch) [inline backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:69]: Maybe we can directly call `SparkResourceUtil.isLocalMaster`?

File: backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala [hunk 3]
```diff
@@ -27,138 +26,67 @@ import org.apache.gluten.vectorized.{JniLibLoader, JniWorkspace}
...
-    // sql table cache serializer
-    if (conf.getBoolean(GlutenConfig.COLUMNAR_TABLE_CACHE_ENABLED.key, defaultValue = false)) {
-      conf.set(
-        StaticSQLConf.SPARK_CACHE_SERIALIZER.key,
-        "org.apache.spark.sql.execution.ColumnarCachedBatchSerializer")
+    if (!driverInitialized.compareAndSet(false, true)) {
+      // Make sure we call the static initializers only once.
+      logInfo(
+        "Skip rerunning static initializers since they are only supposed to run once." +
+          " You see this message probably because you are creating a new SparkSession.")
```
Comment (zml1206) [inline backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: I don’t quite understand that `onDriverStart` will be called multiple times. Can you explain?

Comment (zhztheplayer) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: It happens in Spark local mode. Spark creates one driver and one executor in that mode, in the current process.

Comment (zml1206) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: I understand this. It should be once for `onDriverStart` and once for `onExecutorStart`, not `onDriverStart` is called twice.

Comment (zhztheplayer) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: Oops, got it wrong.

`onDriverStart` will be called twice when spark session is recreated.
`onExecutorStart` may be called twice when dynamic allocation is enabled, I am not sure about this one.

Comment (zml1206) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: Can you give an example of how spark session is recreated, cloneSession or other?

Comment (zml1206) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: About `onExecutorStart`, I think it will not called twice because dynamic allocation add new executor is a new jvm.

Comment (zhztheplayer) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: > Can you give an example of how spark session is recreated, cloneSession or other?

Please refer to `SparkSession.stop` or `SparkContext.stop`

File: backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala (hunk 2 above)
Comment (zhztheplayer) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:69]: I am OK to both... Keeping it would shorten the calling code a little bit

File: backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala (hunk 3 above)
Comment (zml1206) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: If just re-create sparkSession, it will not restart the driver. Re-creating sparkContext will restart the driver, but a new sparkConf may be set, so is it better to re-initialize it once?

Comment (zhztheplayer) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala:47]: Yes, finally we should remove the flags and do re-initializations. See [my comment](https://github.com/apache/incubator-gluten/blob/4096a53e146981ff092c43b56f456137258632b9/backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala#L130-L133) and the issue https://github.com/apache/incubator-gluten/issues/6862

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Review by PHILO-HE — APPROVED** [review]
