### PR TITLE
[GLUTEN-6470][CH]Fix Task not serializable error when inserting mergetree data

### LINKED ISSUE #6470: [CH] Fix Task not serializable error when inserting mergetree data
### Backend

CH (ClickHouse)

### Bug description

When inserting mergetree data, it occurs the `Task not serializable` error in some cases.

RC:
In the Delta, the options of the `DeltaOptions` is a `CaseInsensitiveMap`, if calling the api `filterKeys()` of the `CaseInsensitiveMap`, it may become not serializable, so lead to this error.

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by zzcclp**
## What changes were proposed in this pull request?

When inserting mergetree data, it occurs the Task not serializable error in some cases.

RC:
In the Delta, the options of the `DeltaOptions` is a `CaseInsensitiveMap`, if calling the api `filterKeys()` of the `CaseInsensitiveMap`, it may become not serializable, so lead to this error.

Close #6470.

(Fixes: #6470)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

File: gluten-core/src/main/scala/org/apache/spark/softaffinity/SoftAffinity.scala [hunk 1]
```diff
@@ -39,7 +39,7 @@ abstract class Affinity(val manager: AffinityManager) extends LogLevelUtil with
       filePaths: Array[String],
       preferredLocations: Array[String]): Array[String] = {
     if (shouldUseSoftAffinity(filePaths, preferredLocations)) {
-      internalGetHostLocations(filePaths.min)
+      internalGetHostLocations(filePaths(0))
```
Comment (baibaichen) [inline gluten-core/src/main/scala/org/apache/spark/softaffinity/SoftAffinity.scala:42]: Is this modification related to this issue?

Comment (zzcclp) [reply gluten-core/src/main/scala/org/apache/spark/softaffinity/SoftAffinity.scala:42]: not related

**Review by baibaichen — APPROVED** [review]
LGTM
