### PR TITLE
[GLUTEN-8183][CORE] Prune unused column in project operator

### LINKED ISSUE #8183: [CH] Duplicated expression evaluation in project before aggregate operator due to PullOutPreProject Rule
### Backend

CH (ClickHouse)

### Bug description

In below query, expr `if(id % 2 = 0, id+3, id+4)` was evaluated twice both in `n3` and `_pre_5`. I find that `_pre_5` is introduced by `PullOutPreProject ` in https://github.com/apache/incubator-gluten/issues/4213.   cc @PHILO-HE @zhztheplayer   can you find similar issue in Velox? 
``` sql
explain extended 
select max(n1), max(n2), sum(if(n1+n2+n3 % 2 = 0, 1, 0)) from (select id+1 as n1, id+2 as n2, if(id % 2 = 0, id+3, id+4) as n3 from range(10)) 
```

``` sql 
== Optimized Logical Plan ==
Aggregate [max(n1#375L) AS max(n1)#386L, max(n2#376L) AS max(n2)#387L, sum(if ((((n1#375L + n2#376L) + (n3#377L % 2)) = 0)) 1 else 0) AS sum((IF((((n1 + n2) + (n3 % 2)) = 0), 1, 0)))#389L]
+- Project [(id#383L + 1) AS n1#375L, (id#383L + 2) AS n2#376L, if (((id#383L % 2) = 0)) (id#383L + 3) else (id#383L + 4) AS n3#377L]
   +- Range (0, 10, step=1, splits=None)

== Physical Plan ==
CHNativeColumnarToRow
+- ^(9) HashAggregateTransformer(keys=[], functions=[max(n1#375L), max(n2#376L), sum(_pre_5#396)], isStreamingAgg=false, output=[max(n1)#386L, max(n2)#387L, sum((IF((((n1 + n2) + (n3 % 2)) = 0), 1, 0)))#389L])
   +- ^(9) ProjectExecTransformer [(id#383L + 1) AS n1#375L, (id#383L + 2) AS n2#376L, if (((id#383L % 2) = 0)) (id#383L + 3) else (id#383L + 4) AS n3#377L, if (((((id#383L + 1) + (id#383L + 2)) + (if (((id#383L % 2) = 0)) (id#383L + 3) else (id#383L + 4) % 2)) = 0)) 1 else 0 AS _pre_5#396]
      +- ^(9) InputIteratorTransformer[id#383L]
         +- RowToCHNativeColumnar
            +- *(1) Range (0, 10, step=1, splits=1)
```

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by liujiayi771**
## What changes were proposed in this pull request?

Fix #8183 

## How was this patch tested?

Add a new UT.

### CODE REVIEW

**Comment by liujiayi771** [comment]
Run Gluten Clickhouse CI on x86

**Comment by liujiayi771** [comment]
@taiyang-li @PHILO-HE @ulysses-you Could you help to review?

**Comment by liujiayi771** [comment]
@ulysses-you @PHILO-HE @taiyang-li This PR is ready for review. We didn't notice that we actually added a lot of unnecessary columns to the project.

**Review by ulysses-you — APPROVED** [review]

**Comment by PHILO-HE** [comment]
@liujiayi771, our internal test shows that there is a bit perf. regression on TPCH. Is it related to this pr?

```
query	log/native_8295_time.csv	log/native_master_01_02_2025_time.csv	difference	percentage 
q1	25.94	25.55	-0.390	98.50% 
q2	23.69	24.20	0.518	102.19% 
q3	31.96	32.13	0.171	100.53% 
q4	26.90	26.29	-0.602	97.76% 
q5	58.37	59.65	1.283	102.20% 
q6	9.33	7.54	-1.783	80.88% 
q7	63.33	65.63	2.297	103.63% 
q8	67.45	67.33	-0.124	99.82% 
q9	103.54	96.54	-7.003	93.24% 
q10	43.52	43.03	-0.488	98.88% 
q11	17.66	16.15	-1.510	91.45% 
q12	16.57	15.72	-0.848	94.88% 
q13	28.73	26.35	-2.388	91.69% 
q14	12.22	12.34	0.126	101.03% 
q15	27.88	26.38	-1.503	94.61% 
q16	13.89	13.06	-0.825	94.06% 
q17	81.63	73.48	-8.142	90.03% 
q18	122.34	116.64	-5.694	95.35% 
q19	16.32	22.82	6.508	139.89% 
q20	24.01	23.07	-0.944	96.07% 
q21	192.21	180.51	-11.700	93.91% 
q22	11.04	10.35	-0.691	93.74% 
total	1018.52	984.79	-33.730	96.69% 
```

**Comment by liujiayi771** [comment]
@PHILO-HE According to the TPCH plan golden file, the only change is that the number of columns output by the pre-project before the aggregation has decreased, and there are no other changes at the plan level. Is there any fluctuation?

**Comment by PHILO-HE** [comment]
> @PHILO-HE According to the TPCH plan golden file, the only change is that the number of columns output by the pre-project before the aggregation has decreased, and there are no other changes at the plan level. Is there any fluctuation?

@liujiayi771, just verified the main branch, it has the same regression. So I believe the regression is not caused by your pr.

File: gluten-ut/spark35/src/test/scala/org/apache/spark/sql/extension/GlutenExtensionRewriteRuleSuite.scala [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+ * limitations under the License.
+ */
+package org.apache.spark.sql.extension
+
+import org.apache.gluten.execution.ProjectExecTransformer
+
+import org.apache.spark.SparkConf
+import org.apache.spark.sql.GlutenSQLTestsTrait
+
+class GlutenExtensionRewriteRuleSuite extends GlutenSQLTestsTrait {
```
Comment (PHILO-HE) [inline gluten-ut/spark35/src/test/scala/org/apache/spark/sql/extension/GlutenExtensionRewriteRuleSuite.scala:24]: Maybe, we can move this test into `gluten/gluten-ut/test`, which will make it tested for all supported Spark with just one test file.

**Review by PHILO-HE — COMMENTED** [review]
Looks good! One comment related to test. @taiyang-li, please take a look.

**Review by taiyang-li — APPROVED** [review]
LGTM

**Review by PHILO-HE — APPROVED** [review]
